# Generated by Django 5.1.5 on 2025-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(default='India', max_length=50),
            preserve_default=False,
        ),
    ]
